spring:
  application:
    name: money-transfer-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/money_transfer_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 22bce1313
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  
# Application Configuration
app:
  min-balance: 1000.00

# Default admin user credentials (auto-created on first startup)
admin:
  default:
    email: admin@system.com
    password: admin123
    name: System Administrator
